FROM node:16-alpine as builder

WORKDIR /dist

ADD package.json yarn.lock /dist/
RUN npm install

ADD . /dist

RUN npm run build

# 选择更小体积的基础镜像
FROM nginx:alpine

# 将构建产物移至 nginx 中
COPY --from=builder dist/dist/ /usr/share/nginx/html/